/**
 * Created by Sugar on 2017/8/29.
 */
export default {
  bsdata: {
    // new_enterprisename: "企业名称",

    // new_frname: "法定代表人",
    // new_regno: "工商注册号",
    // new_creditcode: "统一社会信用代码",
    // new_regcap: "注册资金(单位:万元)",
    // new_regcapcur: "注册币种",
    // new_esdate: "开业日期",
    // new_openfrom: "经营期限自",
    // new_opento: "经营期限至",
    // new_enterprisetype: "企业(机构)类型",
    // new_enterprisestatus: "经营状态",
    // new_canceldate: "注销日期",
    // new_revokedate: "吊销日期",
    // new_address: "注册地址",
    // new_abuitem: "许可经营项目",
    // new_cbuitem: "一般经营项目",
    // new_operatescope: "经营(业务)范围",
    // new_operatescopeandform: "经营(业务)范围及方式",

    new_faren: "法人",
    new_regnumber: "登记证号",
    new_creditcode: "信用代码",
    new_regcap: "注册资本",
    new_regmoney: "注册资本",
    new_regdate: "注册日期",
    new_business: "经营期限",
    new_companytype: "机构类型",
    new_businessstatus: "经营状态",
    new_cervalidityperiod: "证书有效期",
    new_companycode: "机构代码",
    // new_companyname: "公司名称",
    // new_companykey: "机构主键",
    new_companysize: "公司规模",
    new_areacode: "区域代码",
    new_areaname: "区域名称",
    new_regorgname: "登记机关",
    new_issuetime: "证件生效日期",
    new_invalidtime: "证件失效日期",
    new_phonearea: "电话区号",
    new_phone: "联系电话",
    // new_provincename: "省份",
    new_email: "企业信箱",
    new_website: "企业网站",
    new_tradedic: "所属行业",
    new_address: "公司地址",
    new_regtype: "注册类型",
    // new_chkdate: "核实日期",
    // new_yearchk: "最近年检",
    new_operatescope: "经营范围",
  },

  //icon
  new_name: "名字-person-text",
  new_comp: "公司-domain-text",
  new_mobile: "手机-phone_iphone-number",
  new_tel: "电话-call-tel",
  new_email: "邮箱-email-email",
  new_dept: "职位-perm_contact_calendar-text",
  new_addr: "地址-place-text",
  new_web: "网址-web-text",
  new_fax: "传真-local_printshop-text",
  new_post: "邮编-markunread_mailbox-number",
  // new_title: "图片地址"
}
